// Generated accessors. Defaults preserve the existing control values.
#define LONG_FAST (CarConfig::active[CarConfig::LONG_FAST_ID] / 100.0f)
#define LONG_MID (CarConfig::active[CarConfig::LONG_MID_ID] / 100.0f)
#define LONG_SLOW (CarConfig::active[CarConfig::LONG_SLOW_ID] / 100.0f)
#define LONG_FF_FAST (CarConfig::active[CarConfig::LONG_FF_FAST_ID])
#define LONG_FF_MID (CarConfig::active[CarConfig::LONG_FF_MID_ID])
#define LONG_FF_SLOW (CarConfig::active[CarConfig::LONG_FF_SLOW_ID])
#define LONG_START_SPEED (CarConfig::active[CarConfig::LONG_START_SPEED_ID] / 100.0f)
#define LONG_START_FF (CarConfig::active[CarConfig::LONG_START_FF_ID])
#define LONG_RAMP_MS (CarConfig::active[CarConfig::LONG_RAMP_MS_ID])
#define LONG_MIN_PWM (CarConfig::active[CarConfig::LONG_MIN_PWM_ID])
#define LONG_MAX_PWM (CarConfig::active[CarConfig::LONG_MAX_PWM_ID])
#define LAT_FAST (CarConfig::active[CarConfig::LAT_FAST_ID] / 100.0f)
#define LAT_MID (CarConfig::active[CarConfig::LAT_MID_ID] / 100.0f)
#define LAT_SLOW (CarConfig::active[CarConfig::LAT_SLOW_ID] / 100.0f)
#define LAT_FF_FAST (CarConfig::active[CarConfig::LAT_FF_FAST_ID])
#define LAT_FF_MID (CarConfig::active[CarConfig::LAT_FF_MID_ID])
#define LAT_FF_SLOW (CarConfig::active[CarConfig::LAT_FF_SLOW_ID])
#define LAT_START_SPEED (CarConfig::active[CarConfig::LAT_START_SPEED_ID] / 100.0f)
#define LAT_START_FF (CarConfig::active[CarConfig::LAT_START_FF_ID])
#define LAT_RAMP_MS (CarConfig::active[CarConfig::LAT_RAMP_MS_ID])
#define LAT_MIN_PWM (CarConfig::active[CarConfig::LAT_MIN_PWM_ID])
#define LAT_MAX_PWM (CarConfig::active[CarConfig::LAT_MAX_PWM_ID])
#define DIAG_FAST (CarConfig::active[CarConfig::DIAG_FAST_ID] / 100.0f)
#define DIAG_MID (CarConfig::active[CarConfig::DIAG_MID_ID] / 100.0f)
#define DIAG_SLOW (CarConfig::active[CarConfig::DIAG_SLOW_ID] / 100.0f)
#define DIAG_FF_FAST (CarConfig::active[CarConfig::DIAG_FF_FAST_ID])
#define DIAG_FF_MID (CarConfig::active[CarConfig::DIAG_FF_MID_ID])
#define DIAG_FF_SLOW (CarConfig::active[CarConfig::DIAG_FF_SLOW_ID])
#define DIAG_START_SPEED (CarConfig::active[CarConfig::DIAG_START_SPEED_ID] / 100.0f)
#define DIAG_START_FF (CarConfig::active[CarConfig::DIAG_START_FF_ID])
#define DIAG_RAMP_MS (CarConfig::active[CarConfig::DIAG_RAMP_MS_ID])
#define DIAG_MIN_PWM (CarConfig::active[CarConfig::DIAG_MIN_PWM_ID])
#define DIAG_MAX_PWM (CarConfig::active[CarConfig::DIAG_MAX_PWM_ID])
#define ROT_FAST (CarConfig::active[CarConfig::ROT_FAST_ID] / 100.0f)
#define ROT_MID (CarConfig::active[CarConfig::ROT_MID_ID] / 100.0f)
#define ROT_SLOW (CarConfig::active[CarConfig::ROT_SLOW_ID] / 100.0f)
#define ROT_FF_FAST (CarConfig::active[CarConfig::ROT_FF_FAST_ID])
#define ROT_FF_MID (CarConfig::active[CarConfig::ROT_FF_MID_ID])
#define ROT_FF_SLOW (CarConfig::active[CarConfig::ROT_FF_SLOW_ID])
#define ROT_START_SPEED (CarConfig::active[CarConfig::ROT_START_SPEED_ID] / 100.0f)
#define ROT_START_FF (CarConfig::active[CarConfig::ROT_START_FF_ID])
#define ROT_RAMP_MS (CarConfig::active[CarConfig::ROT_RAMP_MS_ID])
#define ROT_MIN_PWM (CarConfig::active[CarConfig::ROT_MIN_PWM_ID])
#define ROT_MAX_PWM (CarConfig::active[CarConfig::ROT_MAX_PWM_ID])
#define BRAKE_W_SHORT_TARGET (CarConfig::active[CarConfig::BRAKE_W_SHORT_TARGET_ID])
#define BRAKE_W_LONG_TARGET (CarConfig::active[CarConfig::BRAKE_W_LONG_TARGET_ID])
#define BRAKE_W_SHORT_LEAD (CarConfig::active[CarConfig::BRAKE_W_SHORT_LEAD_ID])
#define BRAKE_W_LONG_LEAD (CarConfig::active[CarConfig::BRAKE_W_LONG_LEAD_ID])
#define BRAKE_S_SHORT_TARGET (CarConfig::active[CarConfig::BRAKE_S_SHORT_TARGET_ID])
#define BRAKE_S_LONG_TARGET (CarConfig::active[CarConfig::BRAKE_S_LONG_TARGET_ID])
#define BRAKE_S_SHORT_LEAD (CarConfig::active[CarConfig::BRAKE_S_SHORT_LEAD_ID])
#define BRAKE_S_LONG_LEAD (CarConfig::active[CarConfig::BRAKE_S_LONG_LEAD_ID])
#define BRAKE_A_SHORT_TARGET (CarConfig::active[CarConfig::BRAKE_A_SHORT_TARGET_ID])
#define BRAKE_A_LONG_TARGET (CarConfig::active[CarConfig::BRAKE_A_LONG_TARGET_ID])
#define BRAKE_A_SHORT_LEAD (CarConfig::active[CarConfig::BRAKE_A_SHORT_LEAD_ID])
#define BRAKE_A_LONG_LEAD (CarConfig::active[CarConfig::BRAKE_A_LONG_LEAD_ID])
#define BRAKE_D_SHORT_TARGET (CarConfig::active[CarConfig::BRAKE_D_SHORT_TARGET_ID])
#define BRAKE_D_LONG_TARGET (CarConfig::active[CarConfig::BRAKE_D_LONG_TARGET_ID])
#define BRAKE_D_SHORT_LEAD (CarConfig::active[CarConfig::BRAKE_D_SHORT_LEAD_ID])
#define BRAKE_D_LONG_LEAD (CarConfig::active[CarConfig::BRAKE_D_LONG_LEAD_ID])
#define BRAKE_Q_SHORT_TARGET (CarConfig::active[CarConfig::BRAKE_Q_SHORT_TARGET_ID])
#define BRAKE_Q_LONG_TARGET (CarConfig::active[CarConfig::BRAKE_Q_LONG_TARGET_ID])
#define BRAKE_Q_SHORT_LEAD (CarConfig::active[CarConfig::BRAKE_Q_SHORT_LEAD_ID])
#define BRAKE_Q_LONG_LEAD (CarConfig::active[CarConfig::BRAKE_Q_LONG_LEAD_ID])
#define BRAKE_E_SHORT_TARGET (CarConfig::active[CarConfig::BRAKE_E_SHORT_TARGET_ID])
#define BRAKE_E_LONG_TARGET (CarConfig::active[CarConfig::BRAKE_E_LONG_TARGET_ID])
#define BRAKE_E_SHORT_LEAD (CarConfig::active[CarConfig::BRAKE_E_SHORT_LEAD_ID])
#define BRAKE_E_LONG_LEAD (CarConfig::active[CarConfig::BRAKE_E_LONG_LEAD_ID])
#define BRAKE_Z_SHORT_TARGET (CarConfig::active[CarConfig::BRAKE_Z_SHORT_TARGET_ID])
#define BRAKE_Z_LONG_TARGET (CarConfig::active[CarConfig::BRAKE_Z_LONG_TARGET_ID])
#define BRAKE_Z_SHORT_LEAD (CarConfig::active[CarConfig::BRAKE_Z_SHORT_LEAD_ID])
#define BRAKE_Z_LONG_LEAD (CarConfig::active[CarConfig::BRAKE_Z_LONG_LEAD_ID])
#define BRAKE_C_SHORT_TARGET (CarConfig::active[CarConfig::BRAKE_C_SHORT_TARGET_ID])
#define BRAKE_C_LONG_TARGET (CarConfig::active[CarConfig::BRAKE_C_LONG_TARGET_ID])
#define BRAKE_C_SHORT_LEAD (CarConfig::active[CarConfig::BRAKE_C_SHORT_LEAD_ID])
#define BRAKE_C_LONG_LEAD (CarConfig::active[CarConfig::BRAKE_C_LONG_LEAD_ID])
#define RUN_TIMEOUT_MS (CarConfig::active[CarConfig::RUN_TIMEOUT_MS_ID])
#define BRAKE_HOLD_MS (CarConfig::active[CarConfig::BRAKE_HOLD_MS_ID])
#define IDLE_BRAKE_HOLD_MS (CarConfig::active[CarConfig::IDLE_BRAKE_HOLD_MS_ID])
#define MID_ZONE_PERCENT (CarConfig::active[CarConfig::MID_ZONE_PERCENT_ID])
#define SLOW_ZONE_PERCENT (CarConfig::active[CarConfig::SLOW_ZONE_PERCENT_ID])
#define WHEEL_KP (CarConfig::active[CarConfig::WHEEL_KP_ID] / 10000.0f)
#define WHEEL_KI (CarConfig::active[CarConfig::WHEEL_KI_ID] / 10000.0f)
#define WHEEL_I_OUT_LIMIT (CarConfig::active[CarConfig::WHEEL_I_OUT_LIMIT_ID] / 100.0f)
#define KR_D (CarConfig::active[CarConfig::KR_D_ID] / 10000.0f)
#define R_MEM_LEAK (CarConfig::active[CarConfig::R_MEM_LEAK_ID] / 10000.0f)
#define K_RMEM (CarConfig::active[CarConfig::K_RMEM_ID] / 10000.0f)
#define R_MEM_LIMIT (CarConfig::active[CarConfig::R_MEM_LIMIT_ID] / 100.0f)
#define MAX_RMEM_CORRECTION (CarConfig::active[CarConfig::MAX_RMEM_CORRECTION_ID] / 100.0f)
#define MAX_R_CORRECTION (CarConfig::active[CarConfig::MAX_R_CORRECTION_ID] / 100.0f)
#define KY_P (CarConfig::active[CarConfig::KY_P_ID] / 10000.0f)
#define KY_D (CarConfig::active[CarConfig::KY_D_ID] / 10000.0f)
#define MAX_Y_CORRECTION (CarConfig::active[CarConfig::MAX_Y_CORRECTION_ID] / 100.0f)
#define KS_D (CarConfig::active[CarConfig::KS_D_ID] / 10000.0f)
#define MAX_S_CORRECTION (CarConfig::active[CarConfig::MAX_S_CORRECTION_ID] / 100.0f)

